// Registre des avatars sélectionnables (assets/avatars/*.png). `require()`
// doit rester statique pour que Metro les embarque dans le bundle — pas de
// construction dynamique du chemin à partir de l'id.
//
// L'id stocké (voir prefs.ts, profiles.avatar_url) est le nom de fichier sans
// extension : une clé stable, indépendante de l'ordre de cette liste. Un id
// d'une génération précédente qui ne correspond plus à rien ici retombe sur
// les initiales (voir Avatar dans components/ui.tsx), pas sur une erreur.

export const AVATARS: Record<string, number> = {
  icon_01: require('../../assets/avatars/icon_01.png'),
  icon_02: require('../../assets/avatars/icon_02.png'),
  icon_03: require('../../assets/avatars/icon_03.png'),
  icon_04: require('../../assets/avatars/icon_04.png'),
  icon_05: require('../../assets/avatars/icon_05.png'),
  icon_06: require('../../assets/avatars/icon_06.png'),
  icon_07: require('../../assets/avatars/icon_07.png'),
  icon_08: require('../../assets/avatars/icon_08.png'),
  icon_09: require('../../assets/avatars/icon_09.png'),
  icon_10: require('../../assets/avatars/icon_10.png'),
  icon_11: require('../../assets/avatars/icon_11.png'),
  icon_12: require('../../assets/avatars/icon_12.png'),
  icon_13: require('../../assets/avatars/icon_13.png'),
  icon_14: require('../../assets/avatars/icon_14.png'),
  icon_15: require('../../assets/avatars/icon_15.png'),
  icon_16: require('../../assets/avatars/icon_16.png'),
  icon_17: require('../../assets/avatars/icon_17.png'),
  icon_18: require('../../assets/avatars/icon_18.png'),
  icon_19: require('../../assets/avatars/icon_19.png'),
  icon_20: require('../../assets/avatars/icon_20.png'),
  icon_21: require('../../assets/avatars/icon_21.png'),
  icon_22: require('../../assets/avatars/icon_22.png'),
  icon_23: require('../../assets/avatars/icon_23.png'),
  icon_24: require('../../assets/avatars/icon_24.png'),
  icon_25: require('../../assets/avatars/icon_25.png'),
  icon_26: require('../../assets/avatars/icon_26.png'),
  icon_27: require('../../assets/avatars/icon_27.png'),
  icon_28: require('../../assets/avatars/icon_28.png'),
  icon_29: require('../../assets/avatars/icon_29.png'),
  icon_30: require('../../assets/avatars/icon_30.png'),
  icon_31: require('../../assets/avatars/icon_31.png'),
  icon_32: require('../../assets/avatars/icon_32.png'),
  icon_33: require('../../assets/avatars/icon_33.png'),
  icon_34: require('../../assets/avatars/icon_34.png'),
  icon_35: require('../../assets/avatars/icon_35.png'),
  icon_36: require('../../assets/avatars/icon_36.png'),
  icon_37: require('../../assets/avatars/icon_37.png'),
  icon_38: require('../../assets/avatars/icon_38.png'),
  icon_39: require('../../assets/avatars/icon_39.png'),
  icon_40: require('../../assets/avatars/icon_40.png'),
  icon_41: require('../../assets/avatars/icon_41.png'),
  icon_42: require('../../assets/avatars/icon_42.png'),
  icon_43: require('../../assets/avatars/icon_43.png'),
  icon_44: require('../../assets/avatars/icon_44.png'),
  icon_45: require('../../assets/avatars/icon_45.png'),
  icon_46: require('../../assets/avatars/icon_46.png'),
  icon_47: require('../../assets/avatars/icon_47.png'),
  icon_48: require('../../assets/avatars/icon_48.png'),
  icon_49: require('../../assets/avatars/icon_49.png'),
  icon_50: require('../../assets/avatars/icon_50.png'),
  icon_51: require('../../assets/avatars/icon_51.png'),
  icon_52: require('../../assets/avatars/icon_52.png'),
  icon_53: require('../../assets/avatars/icon_53.png'),
  icon_54: require('../../assets/avatars/icon_54.png'),
  icon_55: require('../../assets/avatars/icon_55.png'),
  icon_56: require('../../assets/avatars/icon_56.png'),
  icon_57: require('../../assets/avatars/icon_57.png'),
  icon_58: require('../../assets/avatars/icon_58.png'),
  icon_59: require('../../assets/avatars/icon_59.png'),
  icon_60: require('../../assets/avatars/icon_60.png'),
  icon_61: require('../../assets/avatars/icon_61.png'),
  icon_62: require('../../assets/avatars/icon_62.png'),
  icon_63: require('../../assets/avatars/icon_63.png'),
  icon_64: require('../../assets/avatars/icon_64.png'),
  icon_65: require('../../assets/avatars/icon_65.png'),
  icon_66: require('../../assets/avatars/icon_66.png'),
  icon_67: require('../../assets/avatars/icon_67.png'),
  icon_68: require('../../assets/avatars/icon_68.png'),
  icon_69: require('../../assets/avatars/icon_69.png'),
  icon_70: require('../../assets/avatars/icon_70.png'),
  icon_71: require('../../assets/avatars/icon_71.png'),
  icon_72: require('../../assets/avatars/icon_72.png'),
  icon_73: require('../../assets/avatars/icon_73.png'),
  icon_74: require('../../assets/avatars/icon_74.png'),
  icon_75: require('../../assets/avatars/icon_75.png'),
  icon_76: require('../../assets/avatars/icon_76.png'),
  icon_77: require('../../assets/avatars/icon_77.png'),
  icon_78: require('../../assets/avatars/icon_78.png'),
  icon_79: require('../../assets/avatars/icon_79.png'),
  icon_80: require('../../assets/avatars/icon_80.png'),
  icon_81: require('../../assets/avatars/icon_81.png'),
  icon_82: require('../../assets/avatars/icon_82.png'),
  icon_83: require('../../assets/avatars/icon_83.png'),
  icon_84: require('../../assets/avatars/icon_84.png'),
  icon_85: require('../../assets/avatars/icon_85.png'),
  icon_86: require('../../assets/avatars/icon_86.png'),
  icon_87: require('../../assets/avatars/icon_87.png'),
  icon_88: require('../../assets/avatars/icon_88.png'),
  icon_89: require('../../assets/avatars/icon_89.png'),
  icon_90: require('../../assets/avatars/icon_90.png'),
  icon_91: require('../../assets/avatars/icon_91.png'),
  icon_92: require('../../assets/avatars/icon_92.png'),
  icon_93: require('../../assets/avatars/icon_93.png'),
  icon_94: require('../../assets/avatars/icon_94.png'),
  icon_95: require('../../assets/avatars/icon_95.png'),
};

export const AVATAR_IDS = Object.keys(AVATARS);
